package pixelimagedl

// Code generated by stringer -type PortingAlgorithm -linecomment -output port_types_string.go; DO NOT EDIT.

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BasicAlgorithm-0]
	_ = x[AdvancedAlgorithm-1]
	_ = x[ExperimentalAlgorithm-2]
}

const _PortingAlgorithm_name = "basicadvancedexperimental"

var _PortingAlgorithm_index = [...]uint8{0, 5, 14, 26}

func (i PortingAlgorithm) String() string {
	if i >= PortingAlgorithm(len(_PortingAlgorithm_index)-1) {
		return "PortingAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortingAlgorithm_name[_PortingAlgorithm_index[i]:_PortingAlgorithm_index[i+1]]
}
