// Code generated by "stringer -type PortingAlgorithm -linecomment -output port_types_string.go"; DO NOT EDIT.

package pixelimagedl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BasicAlgorithm-0]
	_ = x[AdvancedAlgorithm-1]
	_ = x[ExperimentalAlgorithm-2]
}

const _PortingAlgorithm_name = "basicadvancedexperimental"

var _PortingAlgorithm_index = [...]uint8{0, 5, 13, 25}

func (i PortingAlgorithm) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PortingAlgorithm_index)-1 {
		return "PortingAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortingAlgorithm_name[_PortingAlgorithm_index[idx]:_PortingAlgorithm_index[idx+1]]
}
